remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Rafail Kalenderis]
description: [Projekte]



# Add this to include custom assets
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      css: "css/custom.css"
